functional:
  - Пользователь должен иметь возможность зарегистрироваться на сайте используя электронную почту 
  - Электронная почта для регистрации должена быть действительной
  - Ник должен содержать минимум 3 символа, символа русского/английского языка
  - Пароль должен содержать не менее 6 символов русского, английского языка или спецсимволов
  - Пользователь должен иметь возможность зайти на сайт с помощью "Github"
  - Пользователь должен иметь возможность зайти на сайт с помощью "Discord"
  - Пользователь должен иметь возможность зайти на сайт используя валидный логин и пароль
  - Зарегистрированный пользователь может восстановить забытый пароль по email

  - Пользователь должен иметь возможность создать игру
  - Пользователь должен иметь возможность выбрать сложность при создании игры
  - Пользователь должен иметь возможность поиграть с другом 
  - Пользователь должен иметь возможность поиграть с другим пользователем
  - Пользователь должен иметь возможность поиграть с ботом 
  - Пользователь должен иметь возможность выбрать продолжительность поединка при создании игры
  - Пользователь должен иметь возможность выбрать задачу для игры по названию из списка
  - Пользователь должен иметь возможность выбрать задачу для игры по тегу из списка
  - Пользователь может самостоятельно сдаться во время игры
  - Пользователю  после игры доступен "реванш"
  - Во время игры есть возможность выбора отображения задания и гайда на английском и русском языке
  - Во время игры есть возможность выбора темы отображения (светлая,темная) 
  - Во время игры можно выбрать язык программирования для решения задачи
  - Во время игры пользователю доступно игровое текстовое поле, для написания решения задачи
  - Во время игры все строчки игрового текстового поля пронумерованы
  - Во время игры пользователю доступно для просмотра игровое поле противника в режиме онлайн
  - Во время игры доступно время до окончания игры
  - Победа присуждается первому правильно решившему задачу пользователю
  - Победа присуждается при сдаче противника
  - Победа присуждается при завершении времени у протиника
  - Пользователю за победу принуждаются очки 
  - Правильность решения задания определяет приложение

  - Незарегистрированный пользователь может принять участие в игре только с ботом
  - Незарегистрированный пользователь в игре отображен под ником John Doe
  
  - Пользователь должен иметь возможность просмотреть таблицу лидеров за неделю на главной странице
  - Пользователь должен иметь возможность просмотреть таблицу лидеров за месяц на главной странице
  - Пользователь должен иметь возможность просмотреть таблицу лидеров за все время на главной странице
  
  - Пользователь должен иметь возможность просмотреть топ-лист (рейтинг пользователей) на отдельной странице
  - Пользователь должен иметь возможность фильтровать топ-лист по рангу (первый-последний)
  - Пользователь должен иметь возможность фильтровать топ-лист по оценке (наивысшая-наименьшая)
  - Пользователь должен иметь возможность фильтровать топ-лист сыгранным играм (наибольшее-наименьшее)
  - Пользователь должен иметь возможность фильтровать топ-лист по дате присоединения (первый-последний)
  - Пользователь должен иметь возможность перейти на профиль Githab игрока 
  - Пользователь должен иметь возможность найти игрока по имени 
  - Пользователь должен иметь возможность фильтровать колличество игроков отображаемых на странице (20,30,40,50) 
  
  - Пользователь должен иметь возможность просматривать колличество игроков-онлайн на главной странице
 
  - Пользователю доступен общий чат  на главной странице
  - В общем чате  присутствует возможность выбирать и отправлять смайлы
  - В игре присутствует чат доступный для участников и зрителей
  - В чате игры присутствует возможность выбирать и отправлять смайлы
  - В турнире присутствует чат турнира
  - Чат турнира доступен всем участникам и зрителям турнира
  - Чат турнира также отображен в играх турнира
  - Сообщения и ник пользователей должны отображаться в окне чата

  - На главной странице пользователь может переключаться между лобби, турнирами и историей игр
 
  - В левом  углу шапки сайта расположен лого, если нажать на него, перемещаешься на главную страницу
  
  - В правом углу шапки сайта отображается  количество игроков-онлайн, приглашения на игру, ник, рейтинг, количество очков рейтинга
  
  - Нажав на  "ник" , "рейтинг", "количество очков рейтинга" у пользователя появляется окно, которое содержит следующие строки - "мой профиль", "настройки", "рейтинг пользователей", "задачи", "турниры", "исходный код", "Hexlet", "присоединяйтесь к дискорд", "Tg#codebattle", "выход" 
  
  - Нажав на  "Мой профиль" пользователь может увидеть статистику (круговая диаграмма,в виде треугольника(победы, проиграл, сдался)), завершенные игры, активность , дату регистрации, "оружие" игрока
  
  - Нажав на "Настройки" пользователь может изменить ник, выбрать оружие, найти клан, выбрать тип звука (Dendy, CS, Стандарт, Беззвучный), с помощью ползунка отрегулировать громкость звука
  
  - Нажав на "Рейтинг пользователей" пользователь перемещается на топ-лист
  
  - Нажав на "Задачи"пользователь может ознакомиться со списком задач, у которых в виде таблицы отображено имя, уровень сложности(1-4), теги, происхождение, состояние(активен-неактивен), наглядность(закрытый-общедоступный), действие(показать)
  - Пользователь должен иметь возможность создать новую задачу
  - При создании заданий доступен выбор видимости задачи(публичный, закрытый)
  - Пользователь может редактировать созданные задачи
  - Пользователь может удалить свои созданные задачи
  
  - Нажав на "Турниры" пользователь может ознакомиться со списком турниров,  у которых в виде таблицы отображено имя, тип(команда, индивидуальные), уровень сложности(1-4), состояние (законченные, активные, ожидающие участников, дата и время начала, действие(показать)
  - Пользователь должен иметь возможность создать новый турнир
  - Пользователь создавший турнир может удалить турнир
  - Пользователь создавший турнир может исключать других пользователей
  - Пользователь создавший закрытый турнир может сделать его открытым
  - Закрытый турнир виден только пользователям участвующим в нем, а так же пользователю создавшему его
  - Пользователь может покидать турниры
  - Турниры с открытым  типом доступа  доступны для просмотра и участия всем пользователям
  
  - Нажав на "Исходный код" пользователь попадает на Github разработчика
  
  - Нажав на "Hexlet" пользователь попадает на сайт https://ru.hexlet.io/
  
  - Нажав на "Присоединяйтесь к дискорд" пользователю отправляется приглашение на канал в дискорде
  
  - Нажав на "Tg#codebattle"  пользователю отправляется приглашение на канал в телеграмме
  
  - Нажав на "Выход" пользователь выходит на страницу авторизации
  
  - Пользователь должен иметь возможность сменить язык с английского на русский
  
  - Пользователь должен иметь возможность отправить обратный отзыв о работе приложения
non-functional:
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть удобным на мобильном устройстве
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен быть способен обрабатывать большое количество трафика 
  - Сайт должен открываться на разных разрешених и подстраиваться под них
implicit:
  - Нельзя зарегистрироваться 2 раза на одну электронную почту
  - Ник должен быть уникальным
  - Значение поля "подтверждение пароля" должно совпадать со значением поля "пароль" при регистрации
  - Функция "реванш" игры запускает новую игру с настройками предыдущей, с тем же противником
  - Приватный чат турнира доступен только участникам турнира
  - Одновременно можно участвовать только в одной игре
  - Время в игре движется по типу "обратный отсчет"
