functional:
  - Пользователь должен иметь возможность зарегистрироваться на сайте используя электронную почту 
  - Пользователь должен иметь возможность зайти на сайт с помощью "Github"
  - Пользователь должен иметь возможность зайти на сайт с помощью "Discord"
  - Пользователь должен иметь возможность зайти на сайт используя валидный логин и пароль
  - Пользователь должен иметь возможность восстановить пароль
  - Пользователь должен иметь возможность поиграть без регистрации 
  
  - Пользователь должен иметь возможность создать игру
  - Пользователь должен иметь возможность выбрать сложность при создании игры
  - Пользователь должен иметь возможность поиграть с другом 
  - Пользователь должен иметь возможность поиграть с другим пользователем
  - Пользователь должен иметь возможность поиграть с ботом 
  - Пользователь должен иметь возможность выбрать продолжительность позединка при создании игры
  - Пользователь должен иметь возможность выбрать задачу для игры по названию из списка
  - Пользователь должен иметь возможность выбрать задачу для игры по тегу из списка
  
  - Пользователь должен иметь возможность просмотреть таблицу лидеров за неделю на главной странице
  - Пользователь должен иметь возможность просмотреть таблицу лидеров за месяц на главной странице
  - Пользователь должен иметь возможность просмотреть таблицу лидеров за все время на главной странице
  
  - Пользователь должен иметь возможность просмотреть топ-лист (рейтинг пользователей) на отдельной странице
  - Пользователь должен иметь возможность фильтровать топ-лист по рангу (первый-последний)
  - Пользователь должен иметь возможность фильтровать топ-лист по оценке (наивысшая-наименьшая)
  - Пользователь должен иметь возможность фильтровать топ-лист сыгранным играм (наибольшее-наименьшее)
  - Пользователь должен иметь возможность фильтровать топ-лист по дате присоединения (первый-последний)
  - Пользователь должен иметь возможность перейти на профиль Githab игрока 
  - Пользователь должен иметь возможность найти игрока по имени 
  - Пользователь должен иметь возможность фильтровать колличество игроков отображаемых на странице (20,30,40,50) 
  
  - Пользователь должен иметь возможность просматривать колличество игроков-онлайн на главной странице
  - Пользователь должен иметь доступ к чату расположенный на главной странице
  - На главной странице пользователь может переключаться между лобби, турнирами и историей игр
  - В левом  углу шапки сайта расположен лого, если нажать на него, перемещаешься на главную страницу
  - В правом углу шапки сайта отображается  количество игроков-онлайн, приглашения на игру, ник, рейтинг, количество очков рейтинга
  - Нажав на  "ник" , "рейтинг", "количество очков рейтинга" у пользователя появляется окно, которое содержит следующие строки - "мой профиль", "настройки", "рейтинг пользователей", "задачи", "турниры", "исходный код", "Hexlet", "присоединяйтесь к дискорд", "Tg#codebattle", "выход" 
  - Нажав на  "Мой профиль" пользователь может увидеть статистику (круговая диаграмма,в виде треугольника(победы, проиграл, сдался)), завершенные игры, активность , дату регистрации, "оружие" игрока
  - Нажав на "Настройки" пользователь может изменить ник, выбрать оружие, найти клан, выбрать тип звука (Dendy, CS, Стандарт, Беззвучный), с помощью ползунка отрегулировать громкость звука
  - Нажав на "Рейтинг пользователей" пользователь перемещается на топ-лист
  - Нажав на "Задачи" пользователь может ознакомиться со списком задач, у которых отображено имя, уровень сложности(1-4), теги, происхождение, состояние(активен-неактивен), наглядность(закрытый-общедоступный), действие(показать). ТА
non-functional:
  - требование 3
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть удобным на мобильном устройстве
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен быть способен обрабатывать большое количество трафика 
  - Сайт должен открываться на разных разрешених и подстраиваться под них
implicit:
  - требование 5
  - требование 6
