functional:
  - Пользователь должен иметь возможность зарегистрироваться на сайте используя электронную почту 
  - Пользователь должен иметь возможность зайти на сайт с помощью "Github"
  - Пользователь должен иметь возможность зайти на сайт с помощью "Discord"
  - Пользователь должен иметь возможность зайти на сайт используя валидный логин и пароль
  - Пользователь должен иметь возможность восстановить пароль
  - У пользователя должна быть возможность поиграть без регистрации 
  - Пользователь должен иметь возможность
  - Пользователь должен иметь возможность
  - Пользователь должен иметь возможность
  - Пользователь должен иметь возможность
non-functional:
  - требование 3
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть удобным на мобильном устройстве
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен быть способен обрабатывать большое количество трафика 
  - 
implicit:
  - требование 5
  - требование 6
